palette = 'machinist'

[palettes.machinist]
color_fg0 = '#e9efec'
color_bg0 = '#211e20'
color_bg1 = '#3b3638'
color_bg3 = '#555568'
color_orange = '#94e344'
color_yellow = '#40985e'
color_aqua = '#1a644e'
color_blue = '#04373b'
color_green = '#94e344'
color_purple = '#d65ca6'
color_red = '#e0604f'
